### ISSUE TITLE
Adicionar colaboradores

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/wumpusgrp1#1]
Aceitem e sincronizem.
Grato.

**Comment by alessonrenato** [comment]
todos adicionados, chequem seus emails.

**Comment by RafaelRSPX** [comment]
Adicionado e sincronizado.

**Comment by hgees** [comment]
Fui retirado do grupo 1,
Favor me retirar da lista de colaboradores deste repositório.
Grato.

**Comment by wagner-lucas** [comment]
Adicionado e sincronizado.

**Comment by alessonrenato** [comment]
Ok hericles.

**Comment by alessonrenato** [comment]
colaboradores foram alterados, sincronizem o novo README

**Comment by alessonrenato** [comment]
Confirmem se foram adicionados para fechar a issue.

**Comment by alessonrenato** [comment]
Colaboradores fechado :+1:
