### ISSUE TITLE
agent_arrows(Flecha),

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#10]
Este é um fato interno do simulador.

O agente deve ter um fato próprio pra controlar a qtdd de flechas.

Por exemplo, façam o fato dinâmico: `nflechas(X)` que usar `assert` e `retractall` para marcar se tem 1 ou 0 flechas.

**Comment by RafaelRSPX** [comment]
Com isso podemos utilizar o assert e o retractall para obter a casa que o agente está?

**Comment by drbeco** [comment]
Para "obter" não. Você faz o controle conforme ele anda e tromba.

O mundo não dá essas informações. 

A única coisa que ainda estou liberando é que o agente sempre está iniciando na casa [1,1]. Mas a regra do simulador original diz que o início é numa posição aleatória.

Mas vamos deixar iniciando em [1,1] mesmo por essa versão.

**Comment by drbeco** [comment]
E pode também considerar que o mundo é tamanho 4x4 se assim ficar mais fácil. Porém o agente ficaria mais esperto se isso não fosse definido de antemão, e fosse deixado para ele descobrir.

De qualquer forma, sempre inicie seus programas por ideias mais simples e vá melhorando conforme tiver tempo.

**Comment by caahreginaa** [comment]
Adicionado novo fato dinâmico e totalmente independente para substituir o que estava sendo usado anteriormente e era do simulador.
