### ISSUE TITLE
Fraco de issues

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#11]
O grupo está totalmente parado em relação às atividades no site github.

Não vejo discussões de novos issues, bug reports, comunicação do grupo, nada.

Grupo parado e prazo estourado em várias milestones.

**Comment by RafaelRSPX** [comment]
Peço desculpas em nome do grupo professor. Infelizmente tivemos muito trabalho para a semana passada com o programa do Robots. Além disso, nesta semana teremos provas de outras disciplinas. Mas após isso, faremos o possível para compensar os atraso.
