### ISSUE TITLE
Posicionamento

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/wumpusgrp1#14]
Pessoas, estou tentando implementar o posicionamento atual do agente. Será muito interessante o agente saber sua posição atual.

**Comment by wagner-lucas** [comment]
Concordo, vai ser importante para fazermos a orientação também.

**Comment by RafaelRSPX** [comment]
Exato. Precisamos saber a orientação do agente e já que sabemos que o agente sempre começa na casa (1,1), a orientação do agente vai indicar qual variável vai ser incrementado e decrementado.

**Comment by caahreginaa** [comment]
Creio que este será um predicado muito importante para que em seguida possamos alvar as posições visitas e seguras .

**Comment by caahreginaa** [comment]
Para está função deveremos considerar a casa e o posicionamento do agente quando ele executou a ação: goforward

**Comment by wagner-lucas** [comment]
Eu adicionei a regra nova posição, agora ela atualiza a cabeça da lista. Porém tem um problema, quando é para fazer turnleft, ele não faz e fica parado.

**Comment by RafaelRSPX** [comment]
Um problema:
Quando o agente vai até a extremidade do mapa, por exemplo, até a casa (4,1), a nossa função calcula e retorna a casa (5,1). Acredito que esse problema seja a tentativa da goforward, no caso, o agente tromba na parede, porém a ação ainda sim chama a função ``` novaposicao(O) ``` e consequentemente soma mais 1 na coordenada X da casa (4,1) e retorna o valor (5,1).

**Comment by caahreginaa** [comment]
Uma opção seria colocar uma condição para que não fosse somado mais do que os limites. Ou seja, só sera somado + 1 caso x<4 e só sera subtraído caso x>1.

**Comment by caahreginaa** [comment]
Problema resolvido.
