### ISSUE TITLE
Orientação do agente

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/wumpusgrp1#15]
Adicionei no código um fato dinâmico para orientação do agente inicialmente como a orientação sendo 0. Adicionei também uma função para somar 90° cada vez que o agente virar para a esquerda. Porém, é necessário que a orientação vá até 360° e zere.

**Comment by alessonrenato** [comment]
Resolvi de forma simples Rafael, só fiz o modulo de 360 pela soma S+90, quando o agente for para a orientação 360, ele volta pra 0.
