### ISSUE TITLE
Onde iniciar dynamic

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#17]
O indicador `:-`
é usado pelo prolog para inicializar módulos, classes dinânicas, fazer "include" de bibliotecas, tec.

A linha

    :- dynamic ([agent_flecha/1, wumpus/1, minhacasa/1, orientacao/1]). %fatos dinamicos

Deve estar no início do código, abaixo apenas da linha `:- load_files([wumpus3]).`

**Comment by alessonrenato** [comment]
Obrigado professor, ordem corrigida.
