### ISSUE TITLE
bug no turnleft

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/wumpusgrp1#18]
Pessoas, tem algum problema que estou sem entender qual a causa. Na ação de virar a esquerda na trombada, algo está retornando falso em orientação ou novaposição e o agente não executa a ação.

```
estou_sentindo_uma_treta([_,_,no,yes,no], turnleft):-    %fazer agente virar para esquerda ao sentir trombada
 76     orientacao(O),
 77     novosentidoleft(O).
```

**Comment by drbeco** [comment]
Pergunta: ele só vira a esquerda se a orientação inicial for zero (leste), então ficando com 90 (norte)?

Se estiver em outra orientação, como faz para virar a esquerda?

**Comment by RafaelRSPX** [comment]
Sim. 

Sempre somamos 90 graus à orientação do agente quando ele vira para a esquerda. 
Por exemplo, se o agente tiver a 180º (sentido para o oeste) e ele vira para a esquerda, o sentido fica para 270º (sul).

**Comment by drbeco** [comment]
Repito a pergunta, reformulando: O agente só vira a esquerda se `orientacao(0)` for **verdade**? Porque?

**Comment by RafaelRSPX** [comment]
Ah. Entendi professor. Na verdade, é ``` orientacao(O) ``` com 'O' e não zero. É uma variável que vai recolher o sentido atual do agente para passar para a função ``` novosentidoleft(O)```. Então o agente vira e atualiza a sua orientação para o novo sentido somando 90º , quando vira para a esquerda.

**Comment by drbeco** [comment]
É uma letra? Então ok. Mas use variáveis com nomes mais claros. Por exemplo `Ori` ou `Dir` (direção). Ok? Ou mesmo, há quem prefira, nomes por extenso (`Direcao`, `Orientacao`, `Nariz`, etc)

**Comment by RafaelRSPX** [comment]
Certo professor. Cassia corrigiu o problema e alterou as variáveis. O bug já está resolvido.
