### ISSUE TITLE
casas seguras

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/wumpusgrp1#19]
Gente eu adicionei uma regra casas seguras, para ele pegar as casas adjacentes e ficar adicionando em uma lista, mas quando ele sentir brisa ou fedor ele não faz nenhuma ação.

**Comment by alessonrenato** [comment]
Ele deve estar ignorando esse predicado justamente porque nessas casas a Percepção recebida é diferente.

**Comment by drbeco** [comment]
Fiz `pull` do ramo develop para dar uma ajuda no problema em questão, mas não tem nada lá. O código está desatualizado.

**Comment by drbeco** [comment]
Ok, o código em questão é:

```
casa_segura([no,no,_,_,no], L, Listadecasasegura):-
    %minhacasa([H, T]),
    %adjacentes([H, T], L),
    %not(member([L1,L2,L3,L4], X)),
    append(L, [], Listadecasasegura).
```

Certo?

Primeiro, nomes das variáveis. Normalmente **H** quer dizer o elemento **Head** e **T** quer dizer a lista **[Tail]**. Por isso se usa muito `[H|T]`. Aqui está com vírgula, então não é _head_ e _tail_ e sim os dois primeiros elementos. O melhor seria chamar de `[X, Y]`. Nomes corretos ajudam a entender o código e até a raciocinar melhor.

Agora esse `not(member([L1,L2,L3,L4], X)),` está muito confuso! Tente não usar `not`, mas se for preciso, usar com muito cuidado. E ver melhor como funciona o predicado `member`, ou seja, `member(Elemento, Lista)` e não o contrário. Faça testes direto no _prompt_ do PROLOG

**Comment by wagner-lucas** [comment]
Eu fiz casas seguras ficar atualizando com os dados de casas adjacentes e minha casa, mas ainda tem um problema, ela ainda não salva as posições da jogada anterior, no caso fica mostrando as casas seguras somente da jogada atual.

**Comment by RafaelRSPX** [comment]
Eu irei alterar as variáveis e **H** e **T** para **X** e **Y** respectivamente.

**Comment by RafaelRSPX** [comment]
Acredito que para resover esse problema, podemos utilizar as funções internas do prolog como o ```union``` ou ```list_to_set``` como o professor demonstrou na issue #8. Isso pode salvar uma lista com as casas segura, dado pelas casas adjacentes e a casa atual do agente.

**Comment by RafaelRSPX** [comment]
Fiz a seguinte lógica para casas_seguras:

```
atualiza_casas_seguras(Csa):-
    casas_seguras(Cs),
    append(Csa, Cs, NovaLista1),
    list_to_set(NovaLista1, NovaLista),
    retractall(casas_seguras(_)),
    assert(casas_seguras(NovaLista)).

faz_casas_seguras(Posicao, L, [no,no,_,_,_], Csa):- %casas que sao seguras, com base em casas adjacentes e minha posicao atual%
    append([Posicao], L, Csb),
    list_to_set(Csb, Csa).

faz_casas_seguras(Posicao, _, [_,_,_,_,_], Csa):-
    Csa=[Posicao].

```
Nesse caso, ```casas_seguras``` é um fato dinâmico. A variável ```Cv``` sempre vai ser atualizado para a variável ```NovaLista```

**Comment by RafaelRSPX** [comment]
Com isso, o bug está corrigido.
