### ISSUE TITLE
Release v0.4

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/wumpusgrp1#21]
Já que conseguimos fazer o nosso agente criar uma lista de casas seguras, casas visitas e casas adjacentes. Acredito que podemos lançar a versão v0.4. Com isso, acredito que temos poucos desafios daqui pra frente, que é fazer o nosso agente desviar de buracos e ir para uma casa segura. Se todos estiverem de acordo, lançaremos hoje a versão v0.4.

**Comment by caahreginaa** [comment]
Concordo.

**Comment by wagner-lucas** [comment]
Ok Rafael, concordo em lançar a versão hoje.

**Comment by alessonrenato** [comment]
Como todos concordaram, tag v0.4 fechada.
