### ISSUE TITLE
Casas Supeitas

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/wumpusgrp1#23]
Imagine a seguinte situação:
O agente andou até a casa (3,1) e sentiu uma brisa. Com isso, é necessário criar uma lista com as casas suspeitas, no caso [[3,2], [4,1]].

Implementei a seguite lógica:
```
minhacasa([3,1]).

cv(Cv):-
    Cv=[[1,1], [2,1], [3,1]].
cs(Cs):-
    Cs=[[1,1], [2,1], [3,1], [1,2], [2,2]].
ca(Ca):-
    Ca=[[3,2], [4,1], [2,1]].

csu(Csu):-
    ca(Ca),
    cs(Cs),
    intersection(Cs, Ca, L1),
    subtract(Ca, L1, Csu).
```

Resultado no ```swipl```:
```
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.2.3)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- csu(X).
X = [[3, 2], [4, 1]].
```

**Comment by drbeco** [comment]
Mude o nome de `cs` para algo mais claro (`cseg` ou `casasegura`). Senão vira sopa de letrinhas daqui a pouco. Meu exemplo foi puramente matemático, não serve para programar com essas variáveis tão curtas.

**Comment by alessonrenato** [comment]
Ok professor, esse foi apenas o teste, fiz pequeno só pra agilizar, mas no código será um nome mais legível.

**Comment by caahreginaa** [comment]
Acredito que esta regra de casas suspeitas ira nos ajudar bastante a não cair nos buracos.

**Comment by alessonrenato** [comment]
Eu adicionei ao codigo o fato casas suspeitas e uma regra que a atualiza, mas ainda falta adicionar algumas condiçoẽs na regra.

**Comment by RafaelRSPX** [comment]
Wagner consegui finalizar a regra adicionando uma subtração da lista de casas seguras com a lista de casas suspeitas.
