### ISSUE TITLE
casa_da_frente como fato dinâmico

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#24]
Um fato dinâmico serve para lembrar algo que foi deduzido com algum custo suficiente para justificá-lo.

Não vejo como a dedução da casa da frente pode justificar um `assert/retractall` para a rodada seguinte. Se o agente se move, ou gira, o que é grande parte das ações, tem que deduzir novamente, jogando o custo lá para cima, e tornando a memória desnecessária.

**Comment by RafaelRSPX** [comment]
Professor implementamos desta maneira para que futuramente possamos comparar a casa da frente com a lista de casas seguras para que o agente possa seguir em frente ou não. O fato dinâmico ```casa_da_frente``` facilita o recolhimento do fato para saber qual a casa da frente do agente. Ou seja, toda a vez que quisermos saber qual a casa da frente do agente, só chamamos o fato ```casa_da_frente``` para uma variável qualquer e assim fazer alguma outra operação com esta variável. Gostaria de saber o senhor está de acordo com essa ideia.

**Comment by drbeco** [comment]
Você pode **só chamar** uma _regra_ estática ao invés de só chamar um fato dinâmico. Não muda nada no resto da implementação.

Para saber a casa da frente basta deduzir _a quente_ pelos fatos dinâmicos `posição` e `orientação`. Não precisa lembrar dessa dedução na próxima rodada, pois o agente já terá mudado de lugar e terá que deduzir de novo de qualquer forma. A **memória** nunca está sendo usada (em raras exceções, não o suficiente para justificar uso de memória).

**Comment by RafaelRSPX** [comment]
O senhor tem razão. Vou alterar o código para que o agente sempre deduza a posição da frente.

**Comment by RafaelRSPX** [comment]
Fiz pequenas alterações para deduzir a casa da frente. Agora a função ```faz_frente``` ficou na seguinte maneira:
```
faz_frente([X, Y], Ori, Frente):- 
    Ori==0,
    X1 is X + 1,
    Frente=[X1, Y].
```
Claro, dependendo da orientação do agente, as variáveis X ou Y serão incrementadas ou decrementadas.

**Comment by drbeco** [comment]
Para o caso de `X1 > 4` existem duas possibilidades:

* o predicado `faz_frente` retorna`[5,Y]` (fora da faixa válida). Neste caso o tratamento de erro é feito por quem chamou `faz_frente`.
* o predicado `faz_frente` retorna `[4,Y]`, ou seja, ele retorna a **mesma** casa que o agente está no momento, como se essa casa fosse o resultado de um `goforward` que **trombou** na parede e permanece no mesmo lugar.

Ambas opções são boas e válidas. Resta saber que melhor método se adapta em harmonia com o restante do código.

**Comment by RafaelRSPX** [comment]
Ok. Adicionei a seguinte modificação:
```
faz_frente([X, Y], Ori, Frente):- % caso a casa da frente seja invalida, a casa da frente e' a mesma casa que o agente esta
    Ori==0,
    X1 is X + 1,
    X1>4,
    Frente=[X, Y].
```
Fiz o mesmo para as outras situações, caso o agente trombe na parede na parte inferior do mundo, a casa da frente vai ser a casa atual, indicando que o agente trombou na parede.

**Comment by drbeco** [comment]
Dica:

```
faz_frente([4, Y], 0, [4, Y]).
```

Isso vale para muitos outros predicados, tanto o `faz_frente` como outros.

**Comment by RafaelRSPX** [comment]
Fica bem melhor. Obrigado professor, já adicionei.

**Comment by drbeco** [comment]
Rafael, não tirei da cartola mágica. Veja a curiosa evolução do meu raciocínio:

```
faz_frente([X, Y], Ori, Frente):- 
    Ori==0,
    X1 is X + 1,
    X1>4,
    Frente=[X, Y].

faz_frente([X, Y], Ori, [X, Y]):- 
    Ori==0,
    X1 is X + 1,
    X1>4.

faz_frente([X, Y], 0, [X, Y]):- 
    X1 is X + 1,
    X1>4.

faz_frente([X, Y], 0, [X, Y]):- 
    X > 3.

faz_frente([4, Y], 0, [4, Y]).
```

O único compromisso que não gostei muito foi o último: programação defensiva, melhor usar o sinal de _maior que_ ao de _igual_. Mas aí, feito o compromisso, tem que garantir que nenhuma outra parte do código vai dar bug e pular o `4`

Se preferir, use o penúltimo predicado.

**Comment by RafaelRSPX** [comment]
Certo. Deixei na última forma, ```faz_frente([4, Y], 0, [4, Y])```, e vi que não tem bug pelos testes que fiz.
