### ISSUE TITLE
Fechar milestones atrasadas

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#26]
![image](https://cloud.githubusercontent.com/assets/5805111/11841688/b8cf62f2-a3dd-11e5-9aa0-f5a423e529db.png)

Não deixe milestones abertas. Ao fechar, não esqueça de fazer release (merge no master com tags).

**Comment by alessonrenato** [comment]
Tag adicionada, milestone v0.5 fechada.
