### ISSUE TITLE
Calculacao e alvo

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/wumpusgrp1#27]
Conseguimos implementar o predicado calculacao o que nos fornece uma ação. Porém, precisamos identificar o alvo para este predicado. Acredito que o alvo seja a casa segura não visitada mais próxima do agente, o que pode ser uma das casas adjacentes.

**Comment by caahreginaa** [comment]
Concordo que o alvo deverá ser uma casa segura não visitada, mas não acho que necessariamente uma das casas adjacentes. Podemos usar subtração entre listas para "pegar" casas seguras não visitadas e usá-las como alvo.

**Comment by drbeco** [comment]
Concordo com a Cássia. Mas tem um jeito mais simples que subtrair listas, e isso depende do que você quer no momento.

Ou seja, o alvo muda conforme a fase que o agente se encontra.

* Quer achar o ouro?
* Quer achar o wumpus (deduzir precisamente)?
* Quer matar o wumpus?
* Quer sair?

**Comment by RafaelRSPX** [comment]
Quando o nosso agente visitar todas as casas seguras, podemos definir como alvo a casa [1,1] , fazer ele seguir pelo caminho seguro e sair. Acredito que nossa prioridade inicial é fazer o agente sair, pegando ouro ou não.

**Comment by caahreginaa** [comment]
Concordo. Já que o objetivo principal é sair com a maior quantidade de pontos, melhor ir embora mesmo que sem ouro do que arriscar morrer.

**Comment by wagner-lucas** [comment]
Concordo com vocês, quando ele andar todas ou a maioria das casas seguras, priorizar sair do mapa. Já que em alguns mapas é impossível pegar o ouro, assim a melhor jogada é andar as casas seguras e depois sair.

**Comment by caahreginaa** [comment]
Verdade, Wagner. Quando ele andar todas as seguras também, é hora de sair do mapa. Muitas vezes o ouro ta na mesma casa que buraco, é melhor não arriscar

**Comment by wagner-lucas** [comment]
Então fica fixo a prioridade do agente é sair com vida depois pegar o ouro ou depois que todas as casas seguras e não visitadas esteja vazio.
