### ISSUE TITLE
Quantidade Máxima de ações

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/wumpusgrp1#29]
Estou tentando implementar um fato dinâmico com a quantidade máxima de ações do agente. Quando esse fato atingir o valor máximo, a casa [1,1] se torna prioridade para o agente para ele sair. 
Porém, qual o valor que devemos botar como máximo?

**Comment by alessonrenato** [comment]
Tomando como base o pior caso de 12 ações, poderia ser um número entre 50-54.

**Comment by caahreginaa** [comment]
Rapaz, temos que pensar na pior possibilidade possível, OU SEJA, pensar quantas ações o agente precisaria usar pra voltar caso ele esteja na casa mais distante possivel

**Comment by RafaelRSPX** [comment]
Também acho válido ser entre 50 e 54. Assim sobra algumas ações para ele voltar para a casa [1,1] e sair

**Comment by RafaelRSPX** [comment]
Ok. Vou definir como quantidade máxima sendo 50 ações ok?

**Comment by wagner-lucas** [comment]
concordo com cassia, temos que analisar a maior distancia possível até a casa[1,1], na minha percepção acho que no pior caso ele vai fazer 14 ação até chegar na saída. Então acho que 50 é o ideal.

**Comment by drbeco** [comment]
Um agente inteligente faz 2.875 movimentos por casa. Esse é um valor médio, mas dá para pensar que na ida ele faz mais que a média e na volta faz menos.

**Comment by alessonrenato** [comment]
Esse número sobre o wumpus clássico professor? Porque para calcular isso, tomamos como base que o mundo permite ao agente executar 64 ações, por isso pra que ele não fique parado no meio do mapa, colocamos esse "gap" de +- 12 pra que tenha ações suficientes pra ele voltar.

**Comment by drbeco** [comment]
É sobre o modelo grid quadrado (não o dodecaedro). O grid 4x4 tem 16 casas, e portanto com 64 movimentos máximos, você pode fazer no limite uma média de 4 ações por casa. Mas a média empírica total é apenas 2.875, então tem uma boa margem de erro para o agente conseguir visitar tudo, pegar o ouro, matar o wumpus e sair. A média só do trecho da volta costuma dar em torno de 2.1 ações por casa.

**Comment by alessonrenato** [comment]
Ah, sim entendi agora, estava entendendo o número 2.875 como um número inteiro (dois mil oitocentos e setenta e cinco). Obrigado por explicar professor.
