### ISSUE TITLE
Simulador v.3

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#3]
Cientes que mudou a versão do simulador?

Agora só sorteia 3 buracos!

Use:

`wumpusworld(pit3, 4).`

**Comment by alessonrenato** [comment]
Ok professor.

**Comment by caahreginaa** [comment]
Agente atualizado, professor.

**Comment by RafaelRSPX** [comment]
Ok. Atualizado.

**Comment by wagner-lucas** [comment]
OK professor.

**Comment by drbeco** [comment]
** ATENÇÃO **

Nova atualização. Coloquei uma definição de módulo, para proteger o simulador de acesso indevido do agente.

A única função externa do simulador é a função `start`, para começar o jogo.

O resto é interna e não deve ser usada. Qualquer dedução sobre o mundo o agente deve fazer por si só, por seus próprios meios (e não consultar o simulador).

Atualizem os seus ramos master e develop (`git pull`).

---
Após lerem aqui, o último fechar o bug.

**Comment by caahreginaa** [comment]
Ok professor, entendido.

**Comment by alessonrenato** [comment]
Ok

**Comment by RafaelRSPX** [comment]
Tudo ok.

**Comment by drbeco** [comment]
Associar este issue ao ao milestone "Versão 0,3" com data de 26/11/15
