### ISSUE TITLE
[BUG] Casa anterior

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/wumpusgrp1#30]
Pessoal, tava testando o agente e vi que algumas vezes a casa anterior fixa na casa [1,1] sem o agente ter vindo de lá.

**Comment by RafaelRSPX** [comment]
Deve ter alguma ação que não está atualizando a casa anterior.

**Comment by alessonrenato** [comment]
Fiz um predicado que atualiza a casa anterior. 
```
faz_casa_anterior :- 
    minhacasa(MinhaCasa),
    retractall(casa_anterior(_)),
    assert(casa_anterior(MinhaCasa)).
```
Esse predicado é chamado somente quando o agente dá goforward.

**Comment by alessonrenato** [comment]
Pelos testes que realizei, a casa anterior está sempre se atualizando agora.
