### ISSUE TITLE
Melhoria em calcula ação.

### ISSUE THREAD

**Issue by alessonrenato** [alessonrenato/wumpusgrp1#31]
No programa atual,  o predicado ```calculacao``` só retorna uma ação quando a casa alvo está na mesma linha ou na mesma coluna da casa atual do agente. Acredito que ele deve retornar uma ação que deixe o agente mais próximo do alvo mesmo que o agente não esteja na mesma linha ou coluna do alvo.

**Comment by caahreginaa** [comment]
É verdade. Sugiro criarmos mais cláusulas de calcula ação, para que as mesmas casem com todas as possibilidades.

**Comment by RafaelRSPX** [comment]
Isso. É necessário que este predicado esteja completo para que sempre retorne uma ação para qualquer tipo localização do alvo, no caso atual, o nosso alvo primário é casa [1,1]

**Comment by caahreginaa** [comment]
Adicionei essas cláusulas de calculacao para quando o X e Y forem diferentes
```
calculacao([X1, Y1], 0, [X2, Y2], turnright):-
    X1>X2,
    Y1>Y2,
    novosentidoright.

calculacao([X1, Y1], 0, [X2, Y2], goforward):-
    X1<X2,
    Y1>Y2,
    casas_seguras(CasasSeguras),
    minhacasa(Posicao),
    faz_frente(Posicao, 0, Frente),
    member(Frente, CasasSeguras),
    faz_casa_anterior,
    novaposicao.

calculacao([X1, Y1], 0, [X2, Y2], turnleft):-
    X1>X2,
    Y1<Y2,
    novosentidoleft.

calculacao([X1, Y1], 0, [X2, Y2], goforward):-
    X1<X2,
    Y1<Y2,
    casas_seguras(CasasSeguras),
    minhacasa(Posicao),
    faz_frente(Posicao, 0, Frente),
    member(Frente, CasasSeguras),
    faz_casa_anterior,
    novaposicao.
```

**Comment by RafaelRSPX** [comment]
Ok. Vi que no código, o calculacao para os outros sentidos também estão completos.
