### ISSUE TITLE
Casas seguras e não visitadas

### ISSUE THREAD

**Issue by RafaelRSPX** [alessonrenato/wumpusgrp1#32]
Acredito que nosso programa ficaria mais completo tendo as casas seguras e as casas não visitadas, mostrando ambas as listas.

**Comment by wagner-lucas** [comment]
Já que no nosso código a lista de casas segura dá as casas seguras e não visitadas eu alterei os predicados ```faz_casas_seguras``` para ```faz_casa_seguras_nao_visitadas``` e o nome das variáveis quando a lista de casas seguras é chamado. 
Agora falta implementar o predicado para fazer a lista de casas seguras.

**Comment by RafaelRSPX** [comment]
Ok. Alterei a função ```faz_casas_seguras``` e agora ele inclui a lista de casas visitadas e a lista de casas seguras e não visitadas.
