### ISSUE TITLE
Prioridades

### ISSUE THREAD

**Issue by wagner-lucas** [alessonrenato/wumpusgrp1#33]
Vi no código que uma das primeiras prioridades do agente era sair caso matou o wumpus. Mas acredito que seja melhor que o agente só saia caso ele mate o wumpus **e** visitou todas as casas seguras.

**Comment by RafaelRSPX** [comment]
Isso. Concordo Wagner. Ficaria bem melhor, pois há do agente pegar o ouro e sair com mais pontos ao invés dele simplesmente matar o wumpus e sair.

**Comment by wagner-lucas** [comment]
Adicionei esse condição no seguinte predicado: 
```
estou_sentindo_uma_treta(_, climb) :- 
    minhacasa([1,1]),
    casas_seguras([]),
    wumpus(morto).
```

**Comment by wagner-lucas** [comment]
Assim o agente vai querer explorar o mundo mesmo com o wumpus morto.

**Comment by alessonrenato** [comment]
Sim. Ele deve explorar o mundo mesmo depois de matar o wumpus.

**Comment by caahreginaa** [comment]
Verdade. Temos que visitar o mundo para testar a inteligência do agente.
