### ISSUE TITLE
Fedor do Wumpus e casas suspeitas

### ISSUE THREAD

**Issue by caahreginaa** [alessonrenato/wumpusgrp1#34]
Pessoal, as casas adjacentes ao Wumpus estão sendo marcadas como suspeitas mesmo quando ele esta morto, gostaria de soluções para esse problema, pois o agente não esta andando por elas.

**Comment by RafaelRSPX** [comment]
Ok. Isso é importante para o agente sempre visitar as casas e atualizar a lista de casas seguras para explorar ainda mais o mapa. Conseguisse algo?

**Comment by caahreginaa** [comment]
Eu tinha tentado adicionar uma cláusula de faz_casa_segura que incluísse as adjacentes como seguras caso o agente só sentisse o fedor, mas o Wumpus estivesse morto. Só que aparentemente não funcionou

**Comment by caahreginaa** [comment]
Fiz uma alteração na regra quando o agente ouve o grito de Wumpus, o problema foi solucionado.
