### ISSUE TITLE
Agente atirando sem flechas

### ISSUE THREAD

**Issue by caahreginaa** [alessonrenato/wumpusgrp1#6]
Pessoal, precisamos resolver esse problema do nosso agente. Mesmo apos atirar a flecha e matar o wumpus (ou não), como ele continua sentindo o fedor, continua atirando sem parar e não realiza mais nenhuma ação.

**Comment by RafaelRSPX** [comment]
Uma solução seria finalizar a ação quando o agente ouvisse o grito. Mas provavelmente seria necessário utilizar fato dinâmico.

**Comment by alessonrenato** [comment]
talvez aquela solução de colocar um fato dinâmico resolva

**Comment by wagner-lucas** [comment]
concordo com Rafael, ele realmente vai ter que parar de atirar quando ouvir o grito. mesmo ainda sentindo o fedor, podemos fazer com que ele ignore o fedor depois do grito.  Nesse caso mesmo recebendo uma lista com fedor, ele vai fazer outra ação.

**Comment by drbeco** [comment]
Acho que basta colocar como condição `nflechas(1)` e pronto, tá resolvido isso. Certo?

**Comment by RafaelRSPX** [comment]
Acredito que sim professor, mas o mundo fornece o valor da flecha, a posição que agente se encontra e também o estado do agente. Há alguma forma de recolher essas informações do mundo?

**Comment by drbeco** [comment]
Não, o mundo não fornece nada dessas informações. O agente está cego, surdo e mudo. Por conta e risco.

Qualquer predicado que queira usar tem que ser feito por vocês.

**Comment by caahreginaa** [comment]
Adicionado novo predicado para que a regra relacionada ao "shoot" falhe caso o agente nao possua uma flecha.
