### ISSUE TITLE
Conferir milestones

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#7]
N | Data | Milestone | Descrição
----|----|----|----
1 | 17/11/15 | Versão 0.1 | Criar repositório, rascunhos, clones, ramos, add autores
2 | 19/11/15 | Versão 0.2 | Fazer um agente funcional mínimo que passeie pelo labirinto
3 | 26/11/15 | Versão 0.3 | Colocar alguma inteligência no agente
4 | 03/12/15 | Versão 0.4 | Melhorar as respostas dadas para as percepções do agente
5 | 10/12/15 | Versão 0.5 | Lembrar dos caminhos, casas seguras, pegar o ouro com sucesso
6 | 17/12/15 | Versão 1.0 | Buscar a saída através de caminho seguro. Versão Final
7 | 20/12/15 | Versão 1.1 | Versão final após adiamento.

**Comment by drbeco** [comment]
Faltando corrigir. Criar todos, mesmo atrasados. Associar a eles issues conforme o tema. Acertar as datas de cada um corretamente, com o nome "Versão XXX".

**Comment by drbeco** [comment]
Pessoal, isso é URGENTE. É o primeiro passo, lá da aula inicial que começou o projeto. TODOS OS BUGS dependem disso.

COnferir, renomear, mudar as datas e acertar TODOS milestones.

**Comment by caahreginaa** [comment]
Milestones atualizadas, professor. :smile:

**Comment by drbeco** [comment]
Todos com a data errada (um dia a menos)

**Comment by RafaelRSPX** [comment]
Professor, hoje eu conferi as datas atualizadas dos milestones e todos estão com a data certa. Ontem, @wagner-lucas também viu que as datas estavam com um dia a menos. Mas hoje ele conferiu e confirmou que as datas estão atualizadas e corretas.

**Comment by drbeco** [comment]
Para citar um exemplo:

![image](https://cloud.githubusercontent.com/assets/5805111/11428498/d4424ea2-944a-11e5-8426-242dc4b7ee04.png)


Não conferi os outros. Deixo para vocês.

**Comment by RafaelRSPX** [comment]
Resolvido. Conferi as datas e todas estavam com um dia a menos. Alterei para as datas certas: 
![sem titulo](https://cloud.githubusercontent.com/assets/13755711/11430748/0b1ff7f2-946a-11e5-9eed-020f748cd1ed.png)
