### ISSUE TITLE
adjacentes(Posicao, Lista)

### ISSUE THREAD

**Issue by drbeco** [alessonrenato/wumpusgrp1#8]
Oi pessoal, queria dar uma sugestão importante.

Poderíamos ter uma função que retornasse as casas adjacentes a casa atual (ou a qualquer casa dada).

Por exemplo, se estou na casa `minhaposicao([2,2])` e chamo:

```
minhaposicao(P),
adjacentes(P, L)
```

Então `L=[[3,2], [2,3], [1,2], [2,1]]`

Ou se estou na posição `[1,1]`, então a lista fica apenas com `L=[[2,1], [1,2]]`

Essa função é uma intermediária para depois ser usada em funções mais complexas.

**Comment by drbeco** [comment]
Importante para issue #14

**Comment by drbeco** [comment]
Questão:

Se eu tenho uma lista de casas seguras, uma lista de casa adjacentes e uma lista de casas visitadas, e quero calcular uma lista opções de casas para visitar em seguida, quais operações de conjuntos eu faço? (União, intersecção, subtração, etc.)?

Suponha:

```
CS = lista de casas seguras
CV = lista de casas visitadas
CA = lista de casas adjacentes
CO = lista de opções de casas para visitar nas próximas rodadas
```

Então a fórmula lógica é?

`CO = ??`

---

Operações `PROLOG` para testar:

```
$ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 6.6.6)
Copyright (c) 1990-2013 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- union([[1,1], [2,2]], [[1,1], [3,3]], L).
L = ??

?- list_to_set([[1,1], [2,2], [1,1], [3,3]], L).
L = ??

?- intersection([[1,1], [2,2], [3,3], [2,1]], [[1,1], [2,2], [1,2]], L).
L = ??

?- subtract([[1,1], [2,2], [3,3], [4,4], [2,1]], [[4,4],[2,1],[1,2]], L).
L = ??

?- 
```

Discussão abaixo:

**Comment by wagner-lucas** [comment]
Professor eu acho que tem que ser primeiro subtração entre casas seguras e casas visitadas, assim eu vou saber quais casas são seguras, mas que eu ainda não andei. depois fazemos uma interseção de casas seguras não visitadas, com casas adjacentes. Assim a nossa próxima jogada vai ser uma das casas que a interseção entre essas listas vai retornar.

**Comment by drbeco** [comment]
Tente não diluir sua idéia numa redação. Use uma notação matemática. As nomes que dei acima, sinais de: `-` (para subtração), `+` (para união), `^` (para intersecção).

Então, como ficaria sua resposta colocada em uma fórmula?

```
CO = ??
```

**Comment by RafaelRSPX** [comment]
Acredito que fique assim professor: 
> CO = CA - (CS + CV )

**Comment by wagner-lucas** [comment]
OK professor, minha resposta em notação ficaria assim.
CV - CS = CSN 
CSN^CA= CO

CNS -> casas seguras não visitadas

**Comment by drbeco** [comment]
Ok, coloquem suas ideias para teste. Imaginem listas fictícias e usem os comandos do PROLOG comentados acima, direto no prompt `?-`, sem necessidade de programação.

**Comment by RafaelRSPX** [comment]
Ok. Testarei.

**Comment by RafaelRSPX** [comment]
Professor, uma dúvida. Os comentários que o senhor pôs no agente que explica sobre as percepções e sobre as regra, podemos retirar?

**Comment by drbeco** [comment]
Sim, pode limpar o código como preferir.

**Comment by RafaelRSPX** [comment]
Criei a seguinte função:
```
minhaposicao([H, T]):-
    adjacentes([H, T], L).

adjacentes([H, T], L):-
    cima([H, T], L1),
    baixo([H, T], L2),
    esqueda([H, T], L3),
    direita([H, T], L4),
    L=[L1, L2, L3, L4],
    write('Adjacentes: '),
    writeln(L).

cima([H, T], L1):-
    H1 is H+1,
    L1=[H1, T].

baixo([H, T], L2):-   
    H2 is H-1,
    L2=[H2,T].

esqueda([H, T], L3):-
    T1 is T-1,
    L3=[H,T1].

direita([H, T], L4):-
    T2 is T+1,
    L4=[H,T2].
```
A lista L da regra adjacentes retorna as quatro casas adjacentes, mesmo quando o agente está nas extremidades do mundo. Exemplo:

```
?- minhaposicao([1,1]).
?- Adjacentes: [[2,1],[0,1],[1,0],[1,2]].
```
Quando só deveria retornar as posições : [2,1] e [1,2].

**Comment by drbeco** [comment]
Exemplo:

```
-----------------------------------------
|         |     P   |         |       G |
-----------------------------------------
|         |     P   | W       |         |
-----------------------------------------
|         |         |     P   |         |
-----------------------------------------
|         |   A     |         |         |
-----------------------------------------
```

Suponha que o agente já andou por `[1,1]`, `[2,1]` e `[3,1]` e está de volta para a casa `[2,1]` e agora quer calcular uma casa segura e não visitada e adjacente (no caso a resposta é a casa `[2,2]`). Como fazer?

Faça as listas:

```
CS = lista de casas seguras
CV = lista de casas visitadas
CA = lista de casas adjacentes
```

Faça um teste no prompt do PROLOG com a fórmula por você criada:
```
CO = fórmula? Lista resultante?
```

Mostre a fórmula usando as operações acima (intersecção, união, subtração, ou outra operação de lista/conjunto que precisar), mostre o teste feito no `swipl` (direto no prompt).

**Comment by RafaelRSPX** [comment]
Como o agente andou até a casa [3,1] e voltou para a casa [2,1], a lista de casas visitadas é ```cv([1,1], [2,1], [3,1]).```. A lista de casas seguras vai incluir as casas adjacentes caso o agente não sinta cheiro nem sinta a brisa, sendo assim, a lista de casas segura é ```cs([1,1], [1,2], [2,1], [2,2], [3,1]).```. Como o senhor disse, o agente voltou para a casa [2,1], sendo assim a lista de casas adjacentes é ```ca([1,1], [2,2], [3,1]).```. 

Fiz a seguinte lógica: 
```
cv([1,1], [2,1], [3,1]).
cs([1,1], [1,2], [2,1], [2,2], [3,1]).
ca([1,1], [2,2], [3,1]).

co(L):-
    subtract([[1,1], [1,2], [2,1], [2,2], [3,1]], [[1,1], [2,1], [3,1]], L1), /* L1 = cs - cv */
    intersection(L1, [[1,1], [2,2], [3,1]], L). /* Intersecao L1 e ca */
```

Primeiro faça a subtração das listas de casa segura e casa visitada, ou seja eu quero ir para uma casa segura, porém, não visitada (L1). 
Segundo faça a interseção da lista resultante (L1) com a lista das casas adjacentes.
Isso retorna a lista L que é a próxima casa que o agente deve ir.

Resultado no interpretador:
```
% /home/rdsp/logica/rascunhos/prolog/testes/irpara.pl compiled 0.00 sec, 5 clauses
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 6.6.6)
Copyright (c) 1990-2013 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- co(X).
X = [[2, 2]].
```

**Comment by RafaelRSPX** [comment]
Já que conseguimos implementar a lista de casas seguras, casas adjacentes e de casas vistadas, podemos utilizar esta mesma lógica para fazer o nosso agente seguir pelo caminho mais seguro.

**Comment by drbeco** [comment]
Maravilha. Só um errinho:

```
cv([1,1], [2,1], [3,1]).
cs([1,1], [1,2], [2,1], [2,2], [3,1]).
ca([1,1], [2,2], [3,1]).
```

Assim está indicando `cv/3, cs/5, ca/3`. Devem todos ter um único argumento `/1` que é uma lista:

Deve ser

```
cv([[1,1], [2,1], [3,1]]).
cs([[1,1], [1,2], [2,1], [2,2], [3,1]]).
ca([[1,1], [2,2], [3,1]]).
```

**Comment by wagner-lucas** [comment]
Ok. Professor, entendi. Podemos fazer da seguinte maneira:
```
cv(Cv):-
    Cv=[[1,1], [2,1], [3,1]].
cs(Cs):-
    Cs=[[1,1], [1,2], [2,1], [2,2], [3,1]].
ca(Ca):-
    Ca=[[1,1], [2,2], [3,1]].

co(L):-
    cv(Cv),
    cs(Cs),
    ca(Ca),
    subtract(Cs, Cv, L1), /* L1 = cs - cv */
    intersection(L1, Ca, L). /* Intersecao L1 e ca */

```

Assim todos estarão com um argumento. E a operação pode ser desta maneira:
```
% /home/wlfds/logica/rascunhos/testes/operacao.pl compiled 0.00 sec, 5 clauses
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 6.6.6)
Copyright (c) 1990-2013 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- co(L).
L = [[2, 2]].
```

**Comment by RafaelRSPX** [comment]
Alterei para a milestone v0.5 para adicionar as melhorias na versão mais atual.

**Comment by RafaelRSPX** [comment]
Com o fato dinâmico ```frente``` que vai dar a coordenada da casa da frente, isso permite que podemos testar a casa da frente para que seja igual a um elemento da lista de casas seguras toda vez que o agente fizer a ação turnleft. Quando isso for verdade, o agente pode seguir para frente, quando for falso, o agente deve virar.

**Comment by drbeco** [comment]
`frente` como fato dinâmico? Porque? Tem outro issue para discutir isso melhor?

**Comment by RafaelRSPX** [comment]
Quero dizer, ```casa_da_frente``` como fato dinâmico. Alesson, alterou a função ```frente(Posicao, Sentido, Frente)``` para função ```faz_frente(Posicao, Sentido, Frente)```. Essa função, com essas três variáveis, atualiza o fato dinâmico ```casa_da_frente```.

**Comment by drbeco** [comment]
Discutido no issue #24

**Comment by alessonrenato** [comment]
Tarefa concluída
